export const ENABLE_MEMBERSHIP = false;
export const ENABLE_BLOG_RANKINGS = false;

export const STRIPE_PUBLIC_KEY = 'pk_test_XsgoIEBVG3wbLf1KYYDpYS3900z1sMxY5l';
export const SUBSCRIBER_COUNT = '3,500';

export const YEARLY_SUBSCRIPTION_PRICE_NORMAL = 190;
export const YEARLY_SUBSCRIPTION_PRICE_DISCOUNT = 140;

export const LIFETIME_SUBSCRIPTION_PRICE_NORMAL = 290;
export const LIFETIME_SUBSCRIPTION_PRICE_DISCOUNT = 200;
